config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users, only: [] do
    collection do
      get 'dashboard'
      get 'show'
    end
  end

  resources :trips do
    resources :places, only: [ :show, :edit, :update ] do
      member do
        post 'save_events'
      end
    end
  end

  root to: 'users#show'
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :places
  has_many :events
  accepts_nested_attributes_for :places,
    :allow_destroy => true,
    :reject_if     => :all_blank

  validates :name, presence: true
  validates :arrive, presence: true
  validates :departure, presence: true
  validate  :departure_after_arrive

  private
  def departure_after_arrive
    return if departure.blank? || arrive.blank?

    errors.add(:departure, "cannot be before the arrive")  if departure < arrive
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips?select=:select
  # GET /trips?select=:select.json
  def index
    if (!params.has_key?(:select))
      redirect_to trips_path(select: 'current')
    end
    if (params[:select] == 'previous')
      @trips = current_user.previous_trips
      @title = 'Últimas viagens'
    else
      @trips = current_user.current_trips
      @title = 'Minhas viagens'
    end
  end

  # GET /trips/:id
  # GET /trips/:id.json
  def show
    @places = @trip.places.sort { |a, b| a.arrival <=> b.arrival }
    @plan = @trip.events.map { |e| EventfulApi.get_event(e.eventful_id) }
    Rails.logger.debug @plan[1]
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new
    @trip.places.build
  end

  # GET /trips/:id/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user

    @trip.arrive = @trip.places.min {|a, b| a.arrival <=> b.arrival }.arrival
    @trip.departure = @trip.places.max { |a, b| a.departure <=> b.departure }.departure


    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Sua viagem foi criada.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/:id
  # PATCH/PUT /trips/:id.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Viagem editada.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/:id
  # DELETE /trips/:id.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Viagem removida.' }
      format.json { head :no_content }
    end
  end

  private
  def trip_params
    params.require(:trip).permit(:name, :arrive, :departure,
                                 places_attributes: [:id, :location, :arrival, :departure, :_destroy])
  end

  def set_trip
    @trip = Trip.find_by(id: params[:id])

    if @trip.nil?
      render_404
    elsif @trip.user_id != current_user.id
      render_402
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
  def format_time(str)
    return DateTime.parse(str).strftime("%d/%m/%y %H:%M:%S")
  end
end

app/views/trips/_form.html.erb
<div class="trip-form">
  <%= form_for(@trip) do |f| %>
    <% if @trip.errors.any? %>
      <div id="error_explanation">
        <h2>Não há como salvar essa viagem:</h2>

        <ul>
        <% @trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.text_field :name, placeholder: "Nome da sua viagem", class: "name-form" %>
    </div>
    <h1 class="title">Locais</h1>
      <%= f.fields_for :places do |places_form| %>
        <%= render partial: 'places/field', locals: { places_form: places_form } %>
      <% end %>
    
    <p><%= link_to_add_places "Adicionar novo local", f, :places, 'btn btn-primary confirm-button' %></p>

    <p><%= link_to "Remover novo local", "#", class: 'btn btn-danger confirm-button remove_places' %></p>

    <div class="actions">
      <%= f.submit "Salvar", class: "btn btn-primary confirm-button" %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('form').on('click', '.remove_places', function(event) {
    $(".place_form").last().fadeOut();
    return event.preventDefault();
  });
  
  $('form').on('click', '.add_places', function(event) {
    var regexp, time;
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');
    $(this).before($(this).data('fields').replace(regexp, time));
    return event.preventDefault();
  });
</script>

app/views/trips/edit.html.erb
<div class="card-box">
  <div class="card-box-title">
    <h1>
      Edite sua viagem
    </h1>
  </div>
	<div class="edit-trip-form">
    <%= render 'form', trip: @trip %>
  </div>
</div>

app/views/trips/index.html.erb
<script>
    jQuery(function($) {
        $("tr[data-link]").click(function() {
            window.location = this.dataset.link
        });
    })
</script>
<div class="card-box">
	<div class="card-box-title">
		<h1><%= @title %></h1>
	</div>
	<table class="trips-table">
        <thead class="trips-table-title">
            <tr>
                <th>&nbsp;</th>
                <th>Nome da viagem</th>
                <th>Dia de início</th>
                <th>Dia de fim</th>
            </tr>
        </thead>
        <tbody>
            <% @trips.each do |trip| %>
              <tr class="trips-table-content" data-link="<%= trip_path(trip) %>">
                <td>&nbsp;</td>
                <td><%= trip.name %></td>
                <td><%= date_format(trip.arrive) %></td>
                <td><%= date_format(trip.departure) %></td>
              </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/trips/new.html.erb
<div class="new-trip-box">
    <div class="new-trip-title">
        <h1 class="title">Nova viagem</h1>
    </div>

    <%= render 'form' %>
</div>

app/views/trips/show.html.erb
<script>
jQuery(function($) {
  $("tr[data-link]").click(function() {
    window.location = this.dataset.link
  });
})
</script>
<div class="card-box">
  <div class="card-box-title">
    <h1> <%= @trip.name %> </h1>
  </div>
  <div class="card-single-content">
    <div class="trip-details">
      <ul>
        <li>Data de saída: <%= date_format(@trip.arrive) %></li>
        <li>Data de chegada: <%= date_format(@trip.departure) %></li>
      </ul>
      <table class="places-table">
        <thead class="places-table-title">
          <tr>
            <th>&nbsp;</th>
            <th>Local</th>
            <th>Data de início</th>
            <th>Data de fim</th>
          </tr>
        </thead>
        <tbody>
          <% @places.each do |place| %>
            <tr class="places-table-content" data-link="<%= trip_place_path(@trip, place) %>">
              <td>&nbsp;</td>
              <td><%= place.location %></td>
              <td><%= date_format(place.arrival) %></td>
              <td><%= date_format(place.departure) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br/>
      <%= link_to "Editar", edit_trip_path(@trip), class: "btn btn-primary trip-button-left" %>
      <%= link_to "Excluir", trip_path(@trip), method: :delete, data: { confirm: 'Você tem certeza?' } , class: "btn btn-danger trip-button-right" %>
      <div style="margin-right: 75px; margin-top: 15px;">
      <p>Para escolher os eventos, basta selecionar algum dos locais acima!</p> 
      </div>
    </div>
  </div>
</div>
<div class="card-box">
  <div class="card-box-title">
    <h1>
      Plano de viagem
    </h1>
  </div>
  <% unless @plan.empty? %>
    <div class="events-list">
      <table class="events-table">
        <thead class="events-table-title">
          <tr>
            <th>&nbsp;</th>
            <th>Evento</th>
            <th>Localização</th>
            <th>Horário</th>
          </tr>
        </thead>
        <tbody>
          <% @plan.each do |event| %>
            <tr class="events-table-content" onclick="window.open('<%=event['url']%>2','_blank')">
              <td>&nbsp;</td>
              <td><%= event["title"][0,75] %></td>
              <td><%= event["city"] +', ' + event["country"] %></td>
              <td><%= event["start_time"].strftime("%d/%m/%Y %H:%M") %><%= " - " + event["stop_time"].strftime("%d/%m/%Y %H:%M") unless event["stop_time"].nil? %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p align="center" style="margin-top: 5px;">Você ainda não fez seu plano de viagem! Clique em algum local a ser visitado acima para começar a planejar :)</p>
  <% end %> 
</div>