config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users, only: [] do
    collection do
      get 'dashboard'
      get 'show'
    end
  end

  resources :trips do
    resources :places, only: [ :show, :edit, :update ] do
      member do
        post 'save_events'
      end
    end
  end

  root to: 'users#show'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips, dependent: :destroy
  has_many :previous_trips, -> { where("departure < ?", DateTime.now).order(departure: :asc) }, :class_name => "Trip", :source => :trips
  has_many :current_trips, -> { where("departure >= ?", DateTime.now).order(departure: :asc) }, :class_name => "Trip", :source => :trips
  
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Validation
  #validates_confirmation_of :password
  validates :first_name, :last_name, presence: true
  validates_format_of :first_name, :last_name, :with => /\A([A-Z]*[a-z]+[\s]*)+\z/

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="card-box">
  <div class="card-box-title">
    <h1>Dashboard</h1>
  </div>
  <div class="card-group">
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Nova viagem</h4>
        <p class="card-text">Comece planejando sua nova viagem.</p>
        <%= link_to "Nova viagem", new_trip_path, class: "btn btn-primary card-button" %>
      </div>
    </div>
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Viagens atuais</h4>
        <p class="card-text">Veja suas viagens atuais.</p>
        <%= link_to "Minhas Viagens", trips_path(:select => 'current'), class: "btn btn-primary card-button" %>
      </div>
    </div>
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Últimas viagens</h4>
        <p class="card-text">Veja as últimas viagens que você fez!</p>
        <%= link_to "Últimas viagens", trips_path(:select => 'previous'), class: "btn btn-primary card-button" %>
      </div>
    </div>
  </div>
</div>