config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users, only: [] do
    collection do
      get 'dashboard'
      get 'show'
    end
  end

  resources :trips do
    resources :places, only: [ :show, :edit, :update ] do
      member do
        post 'save_events'
      end
    end
  end

  root to: 'users#show'
end

app/models/place.rb
class Place < ApplicationRecord
	serialize :events, Array

  belongs_to :trip, required: false

  validates :location, presence: true
  validates :arrival, presence: true
  validates :departure, presence: true
  validate  :departure_after_arrival

  def arrival_date_format
    self.arrival.day.to_s + "/" + self.arrival.month.to_s + "/" + self.arrival.year.to_s
  end

  def departure_date_format
    self.departure.day.to_s + "/" + self.departure.month.to_s + "/" + self.departure.year.to_s
  end

  private
  def departure_after_arrival
    return if departure.blank? || arrival.blank?

    errors.add(:departure, "cannot be before the arrival")  if departure < arrival
  end

end

app/controllers/places_controller.rb
require 'eventful_api'

class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy, :save_events]
  helper TripsHelper

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @events = EventfulApi.search(@place.location, @place.arrival, @place.departure)
    @current_events = @trip.events.map { |e| e.eventful_id }
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @place.trip_id = params[:trip_id]

    respond_to do |format|
      if @place.save
        format.html { redirect_to edit_trip_path(@place.trip), notice: 'Lugar criado com sucesso.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to trip_place_path(@trip, @place), notice: 'Lugar atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Lugar removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  # POST /places/1/save_events
  def save_events
    if params.has_key? :events or params.has_key? :last_events
      respond_to do |format|
        if params.has_key? :events
          params[:events].each do |e_id| 
            if @trip.events.where(eventful_id: e_id).empty? 
              Event.create(trip: @trip, eventful_id: e_id)
            end
          end
        end
        if params.has_key? :last_events
          params[:last_events].each do |e_id, was_included|
            event = Event.where(eventful_id: e_id).first
            if event and was_included and not (params.has_key? :events and params[:events].include? e_id)
              event.destroy
            end
          end
        end

        format.html { redirect_to trip_path(@trip), notice: 'Plano de viagem atualizado!' }
        format.json { render :show, status: :ok, location: @trip }
      end
    else
      redirect_to trip_place_path(@trip, @place)
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @trip = Trip.find_by(id: params[:trip_id])
    @place = Place.find_by(id: params[:id])
    if not @trip or not @place
      render_402
    elsif @trip.user_id !=  current_user.id
      render_404
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def place_params
    params.require(:place).permit(:location, :arrival, :departure)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_field.html.erb
<div class="place_form">
  <ul>
    <li>
      <div class="field">
        <%= places_form.text_field :location, placeholder: "Localização", class: "name-form" %>
      </div>
      <div class="field">
        <%= places_form.label "Dia de chegada" %><br>
        <div class="date-form">
          <%= places_form.date_select :arrival, min: Date.today, order: [:day, :month, :year], :use_month_names => ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro','Dezembro'] %>
        </div>
      </div>
      <div class="field">
        <%= places_form.label "Dia de saída" %><br>
        <div class="date-form">
          <%= places_form.date_select :departure, min: Date.today, order: [:day, :month, :year], :use_month_names => ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro','Dezembro'] %>
        </div>
      </div>
      <% if places_form.object.persisted? %>
        <%= places_form.check_box :_destroy %>
        <%= places_form.label :_destroy, "Destroy" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/places/_form.html.erb
<%= form_for(:places) do |f| %>
  <!--
  < if place.errors.any? %>
    <div id="error_explanation">
      <h2>Não há como salvar esse Local:</h2>

      <ul>
      < place.errors.full_messages.each do |message| %>
        <li><message %></li>
       end 
      </ul>
    </div>
   end 
  --> 
  <div class="field">
    <%= f.text_field :location, placeholder: "Localização", class: "name-form" %>
  </div>
  <div class="field">
    <%= f.label "Dia de chegada" %><br>
    <div class="date-form">
      <%= f.date_select :arrive, min: Date.today, order: [:day, :month, :year], :use_month_names => ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro','Dezembro'] %>
    </div>
  </div>
  <div class="field">
    <%= f.label "Dia de saída" %><br>
    <div class="date-form">
      <%= f.date_select :departure, min: Date.today, order: [:day, :month, :year], :use_month_names => ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro','Dezembro'] %>
    </div>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= form_for @place, as: :place, method: :put, url: trip_place_path(@place.trip, @place) do |f| %>
	<% if @place.errors.any? %>
		<div id="error_explanation">
			<h2>Não há como salvar esse local:</h2>

			<ul>
			<% @place.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.text_field :location, placeholder: "Localização", class: "name-form" %>
	</div>
	<div class="field">
		<%= f.label "Dia de chegada" %><br>
		<div class="date-form">
			<%= f.date_select :arrival, min: @place.arrival, order: [:day, :month, :year], :use_month_names => ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro','Dezembro'] %>
		</div>
	</div>
	<div class="field">
		<%= f.label "Dia de saída" %><br>
		<div class="date-form">
			<%= f.date_select :departure, min: @place.departure, order: [:day, :month, :year], :use_month_names => ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro','Dezembro'] %>
		</div>
	</div>

	<div class="actions">
		<%= f.submit "Salvar", class: "btn btn-primary" %>
		<%= link_to 'Voltar', trip_path(@place.trip), class: "btn btn-danger" %>
	</div>
<% end %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
				<td><%= place.name %>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

app/views/places/show.html.erb
<div class="card-box">
  <div class="card-box-title">
    <h1>
      <span class='glyphicon glyphicon-map-marker'></span>&nbsp;<%= @place.location %>
  </h1>
  </div>
  <div class="card-single-content">
    <div class="trip-details">
      <ul>
        <li>Data de saída: <%= date_format(@place.arrival) %></li>
        <li>Data de chegada: <%= date_format(@place.departure) %></li>
      </ul>
      <%= link_to "Editar", edit_trip_place_path, class: "btn btn-primary trip-button-left" %>
      <%= link_to "Excluir", trip_place_path(@place.trip, @place), method: :delete, data: { confirm: 'Você tem certeza?' } , class: "btn btn-danger trip-button-right" %>
    </div>
  </div>

  <h2> Escolha seus eventos para este local: </h2>
   
  <% unless @events.empty? %>
    <%= form_tag save_events_trip_place_path, method: :post do %>
      <div class="events-list">
        <table class="events-table">
          <thead class="events-table-title">
            <tr>
              <th>&nbsp;</th>
              <th>Evento</th>
              <th>Horário</th>
            </tr>
          </thead>
          <tbody>
            <% @events.each do |event| %>
              <tr class="events-table-content">
                <td style="padding-left: 5px;">
                <%= hidden_field_tag 'last_events['+event["id"]+']', (@current_events.include? event["id"]) %>
                <%= check_box_tag 'events[]', event["id"], checked=(@current_events.include? event["id"]) %></td>
                <td onclick="window.open('<%=event['url']%>2','_blank')"><%= event["title"][0,75] %></td>
                <td onclick="window.open('<%=event['url']%>2','_blank')"><%= event["start_time"].strftime("%d/%m/%Y %H:%M") %><%= " - " + event["stop_time"].strftime("%d/%m/%Y %H:%M") unless event["stop_time"].nil? %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="save-plan-button">
        <%= submit_tag 'Salvar meu plano', class: "btn btn-primary" %>
      </div>
    <% end %>
  <% else %>
    <p>Infelizmente não conseguimos encontrar eventos em <%= @place.location %>.  Mesmo assim, não deixe de viajar!</p>
  <% end %>
</div>